### ISSUE TITLE
Where can I get the extraction password for the AUC Distracted Driver Dataset.zip on Kaggle?

### ISSUE THREAD

**Issue by sakiken** [bahetibhakti/Distracted-Driver-Detection#2]
Excuse me for interrupting, could you provide the extraction password for the AUC Distracted Driver Datasetv2.zip that you shared on Kaggle, or could you directly provide the dataset? My email address is [sakikency01@gmail.com]. I have already sent you an email with the attached agreement. I sincerely hope you can reply to me. Thank you.
Best regards.

**Comment by hhfdflw** [comment]
Do you have the AUC Distracted Driver dataset? Could you share it with me, or how can I obtain this dataset?My email address is[hanghuaif@163.com].I'd appreciate it if you could get back to me.Thank you.
